#!/bin/sh /etc/rc.common
NAME=EsurfingShell
DESCRIPTION="EsurfingShell Daemon."
USE_PROCD=1
START=99

config_esfshell_start() {
    config_get_bool enabled $1 enabled 0
    [ "$enabled" = "1" ] || { return 1; }
    config_get username $1 username
    config_get password $1 password
    config_get interface $1 interface
    config_get env $1 env

    procd_open_instance "esfshell_${1}"
    procd_set_param respawn
    procd_set_param env _ES_ACC_USERNAME="$username" _ES_ACC_PASSWD="$password" _ES_GLOBAL_DEVICE="$interface" _ES_HOMEPATH="/etc/esfshell/$interface" $env
    procd_set_param command /usr/bin/esfshell -D
    procd_set_param stdout 1
    procd_close_instance
}

config_esfshell_stop() {
    config_get_bool enabled $1 enabled 0
    [ "$enabled" = "1" ] || { return 1; }
    config_get username $1 username
    config_get password $1 password
    config_get interface $1 interface
    config_get env $1 env

    export _ES_ACC_USERNAME="$username"
    export _ES_ACC_PASSWD="$password"
    export _ES_GLOBAL_DEVICE="$interface"
    export _ES_HOMEPATH="/etc/esfshell/$interface" 
    for ex_env in $env; do
        export $ex_env
    done

	/usr/bin/esfshell -O
}

start_service() {
    config_load esfshell
    config_foreach config_esfshell_start
}

service_stopped() {
    config_load esfshell
    config_foreach config_esfshell_stop
}
