#!/bin/sh /etc/rc.common
NAME=EsurfingShell
DESCRIPTION="EsurfingShell Daemon."
USE_PROCD=1
START=99
ES_HOMEPATH=/etc/esfshell

start_service() {
    local count=0
    for folder in $(ls $ES_HOMEPATH); do
        if [ -d "$ES_HOMEPATH/$folder" ]; then
            procd_open_instance esfshell_$folder
            procd_set_param respawn
            procd_set_param env _ES_HOMEPATH=$ES_HOMEPATH/$folder _ES_GLOBAL_DEVICE=$folder
            procd_set_param command /usr/bin/esfshell -D
            procd_set_param stdout 1
            procd_close_instance
            let count++
        fi
    done
    if [[ $count == 0 ]]; then
        procd_open_instance esfshell
        procd_set_param respawn
        procd_set_param env _ES_HOMEPATH=$ES_HOMEPATH
        procd_set_param command /usr/bin/esfshell -D
        procd_set_param stdout 1
        procd_close_instance
    fi
}

service_stopped() {
    local count=0
    for folder in $(ls $ES_HOMEPATH); do
        if [ -d "$ES_HOMEPATH/$folder" ]; then
            logger -t esfshell $(_ES_HOMEPATH=$ES_HOMEPATH/$folder _ES_GLOBAL_DEVICE=$folder /usr/bin/esfshell -O)
            let count++
        fi
    done
    if [[ $count == 0 ]]; then
        logger -t esfshell $(_ES_HOMEPATH=$ES_HOMEPATH/$folder /usr/bin/esfshell -O)
    fi
}
