#!/bin/sh /etc/rc.common
NAME=EsurfingShell
DESCRIPTION="天翼校园Shell脚本"
USE_PROCD=1
START=99

start_service()
{
    procd_open_instance esfshell
    procd_set_param respawn
    procd_set_param env _ES_HOMEPATH=/路径/到你的/esfshell/主目录
    procd_set_param command /路径/到你的/esfshell -D
    procd_set_param stdout 1
    procd_close_instance
}

stop_service()
{
    /路径/到你的/esfshell -O
}